### ISSUE TITLE
Notation for open intervals

### ISSUE THREAD

**Issue by blefloch** [ribault/CFT-Review#4]
Some open intervals are denoted with the French notation, while others use the English notation.  For instance, equation (3.1.61) reads `[25,∞[` while Exercise 3.3 uses `(0,Q)`.

**Comment by ribault** [comment]
Good point, one more thing to do in the next revision, which will hopefully be done this spring.

**Comment by ribault** [comment]
Switched to French notation, hoping I did not forget some intervals.
