### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by blefloch** [ribault/CFT-Review#5]
I'll collect here typos I find in the arXiv version

- "contolled" => "controlled" p. 36
- In eq (3.2.6) the last exponent should be Delta2-Delta3-Delta1.

**Comment by blefloch** [comment]
eq (3.1.49) does not make it clear whether t belongs to the argument of the sinh^2 or not.  Presumably it does, in which case additional parentheses are needed.

**Comment by ribault** [comment]
Good points, thank you. To be included in next revision.

**Comment by ribault** [comment]
Fixed in new version.
