### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by blefloch** [ribault/CFT-Review#6]
- Below (1.2.14), in "necessary for building a quantum theory from the classical theory", the word "from" is misspelled as "form".
- In "We will mostly justify these further assumptions by formal considerations, which are not physically or mathematically unavoidable." (above (1.3.5)), the double negation seems to be unwanted; I would remove "not".  But perhaps I misunderstood.

**Comment by ribault** [comment]
Thank you for the typo. I also tried to clarify the paragraph above (1.3.5). I think the original formulation was correct, but probably not clear.
