### ISSUE TITLE
"Closure under fusion" axiom seems to exclude E_8 minimal model

### ISSUE THREAD

**Issue by blefloch** [ribault/CFT-Review#7]
Consider the non-diagonal unitary minimal model (E_8,A_30), whose spectrum is for instance given in Table 3 of https://arxiv.org/pdf/0911.3242 (page 9).  The fusion of the representation with Kač labels (7,1) with itself allows (1,1), (3,1), ..., (13,1), as given for instance in equation (7.70) of Di Francesco's CFT book.  Not all of these representations appear in the spectrum of the (E_8,A_30) model.

Something similar happens for the E_6 minimal model I think, but not for the D-type and E_7 type ones.

I'm probably just confused by how the fusion multiplicities are defined.

**Comment by ribault** [comment]
Good remark. I am not sure I understand which value(s) of p are allowed for (E_8,A_{p-1}) modular invariants, or why Cappelli and Zuber talk about "six exceptional cases (E, A), (A, E)", if p can take several values. Assuming (E_8, A_30) exists, then indeed it violates the axiom of closure under fusion, and either the axiom should be modified (but how?), or it should be stated that the axiom eliminates some interesting CFTs (as other axioms do).

**Comment by blefloch** [comment]
[One of Cappelli-Itzykson-Zuber's original papers](http://dx.doi.org/10.1007/BF01221394) is a bit more explicit in Table 2 (p.20).  Minimal models are labeled by two simply laced Lie algebras whose Coxeter numbers p, p' are coprime.  The model is unitary if |p-p'|=1.

The Coxeter number of A_n is n+1, that of D_n is 2n-2, those of E_6, E_7, E_8 are 12, 18, 30.  So for instance (A_{28},E_8) and (A_{30}, E_8) are both unitary.  Exchanging the two Lie algebras amounts to a parity transformation.

I think when Cappelli and Zuber count 6 exceptional cases they are counting the (E_6,A_...), (E_7,A_...), (E_8,A_...), (A_...,E_6), (A_...,E_7), (A_...,E_8) series.  Alternatively they may be counting the exceptional minimal models up to parity, so (E_r,A_{h-2}), (E_r,A_h) for (r,h) among (6,12), (7,18), (8,30).

**Comment by ribault** [comment]
Thank you for the explanations. So indeed closure under fusion kills some minimal models. I think this axiom is nevertheless very helpful for deriving spectrums of a number of models. So I modified the text by keeping the axiom while adding a caveat.

**Comment by blefloch** [comment]
Thanks!
